"""Initial migration

Revision ID: 8940dcc4506a
Revises: 
Create Date: 2025-10-27 09:06:18.210066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8940dcc4506a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neighborhood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('neighborhood', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_neighborhood_name'), ['name'], unique=True)

    op.create_table('measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('clima', sa.JSON(), nullable=True),
    sa.Column('qualidade_do_ar', sa.JSON(), nullable=True),
    sa.Column('qualidade_da_agua', sa.JSON(), nullable=True),
    sa.Column('riscos', sa.JSON(), nullable=True),
    sa.Column('neighborhood_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhood.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('neighborhood_id', 'timestamp', name='uq_neigh_time')
    )
    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurement_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurement_timestamp'))

    op.drop_table('measurement')
    with op.batch_alter_table('neighborhood', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_neighborhood_name'))

    op.drop_table('neighborhood')
    # ### end Alembic commands ###
